name: flutterbyrhyme
description: A  Flutter course.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  url_launcher: ^5.4.2
  shared_preferences: ^0.5.6+2
  html: any
  http: ^0.12.0
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
  - images/
  - assets/

  fonts:
    - family: qlYouYuan
      fonts:
        - asset: fonts/qlYouYuan.ttf
